# Recipe 11 (variant): DENY egress from app=foo but allow DNS (port 53)
# On OCP, for DNS to cluster only use allow-dns-egress-openshift.yaml or add to: openshift-dns
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: foo-deny-egress-allow-dns
spec:
  podSelector:
    matchLabels:
      app: foo
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
